name = "QuadDIRECT"
uuid = "dae52e8d-d666-5120-a592-9e15c33b8d7a"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PositiveFactorizations = "85a6dd25-e78a-55b7-8502-1745935b8125"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
PositiveFactorizations = "0.2"
StaticArrays = "0.10, 0.11, 0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
